# Name of website
title: novathesis word template

# Description of website
description: A Word template for thesis, dissertations and similar monograph-like documents at FCT-NOVA

# Your name to show in the footer
author: João M. Lourenço

# logo
logo: novathesis-word-logo-v5.svg

show_downloads: true
theme: jekyll-theme-minimal
google_analytics: G-MCRPNKMY9J