# Name of website
title: novathesis Word template

# Description of website
description: A Word template for thesis, dissertations and similar monograph-like documents at FCT-NOVA

# Your name to show in the footer
author: João M. Lourenço

# logo
logo: https://joaomlourenco.github.io/novathesis/NOVAthesisFiles/Images/novathesis-logo.jpg

show_downloads: true
theme: jekyll-theme-minimal