################################
# Site Settings
################################
logo        : novathesis-word-logo-v5.svg
title       : "&nbsp;"
description : "A Word template for thesis, dissertations and similar monograph-like documents at FCT-NOVA"
author      : João M. Lourenço
email       : joao.lourenco@fct.unl.pt
show_downloads : true
github:
    zip_url     : https://github.com/joaomlourenco/novathesis_word/zipball/master
    tar_url     : https://github.com/joaomlourenco/novathesis_word/tarball/master

################################
# Theme Settings
################################

theme: jekyll-theme-minimal

################################
# Analytics Settings
################################
google_analytics: G-MCRPNKMY9J
google_tag_manager: G-MCRPNKMY9J
