################################
# Site Settings
################################
logo        : novathesis-word-logo-v5.svg
title       : ""
description : "A Word template for thesis, dissertations and similar monograph-like documents at FCT-NOVA"
author      : João M. Lourenço
email       : joao.lourenco@fct.unl.pt
show_downloads : true
zip_url     : https://github.com/joaomlourenco/novathesis/archive/refs/heads/master.zip
tar_url     : https://github.com/joaomlourenco/novathesis/archive/refs/heads/master.tar.gz

################################
# Theme Settings
################################

theme: jekyll-theme-minimal

################################
# Analytics Settings
################################
google_analytics: G-MCRPNKMY9J
google_tag_manager: G-MCRPNKMY9J
