# Name of website
title: novathesis word template

# Description of website
description: A Word template for thesis, dissertations and similar monograph-like documents at FCT-NOVA

# Your name to show in the footer
author: João M. Lourenço

# logo
logo: novathesis-logo-grey-white-v3.1-1000x201.jpg

show_downloads: true
theme: jekyll-theme-minimal